### ISSUE TITLE
no releases?

### ISSUE THREAD

**Issue by Xmoguz** [Sorax5/SoraxPhysic#1]

**Comment by Xmoguz** [comment]
i cant download lmao

**Comment by Sorax5** [comment]
I'll see about a release very soon. Note that the plugin is in a very unstable state and doesn't work perfectly, it depends on worldedit.

**Comment by Xmoguz** [comment]
Sorax, i dont care about the issues right now, i can fix them myself, i just dont feel like making one from scratch

**Comment by Xmoguz** [comment]
and also, do you possibly have a discord server where we could talk in instead of github?

**Comment by Xmoguz** [comment]
but, i would really appriciate a beta release!

**Comment by Sorax5** [comment]
I don't have a server dedicated to the plugin but you can send me a message on discord with the id soraxdubbing.
I'll check for release I just have a very low coo if I upload from home.

**Comment by Sorax5** [comment]
look in the github action you can download the build
https://github.com/Sorax5/SoraxPhysic/actions/runs/10422395441
